//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "access_sessions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    pub door_device_id: Uuid,
    pub opened_at: DateTimeWithTimeZone,
    pub expires_at: DateTimeWithTimeZone,
    pub status: super::sea_orm_active_enums::SessionStatus,
    pub consumed_by_box_device_id: Option<Uuid>,
    pub closed_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::access_events::Entity")]
    AccessEvents,
    #[sea_orm(has_many = "super::checkouts::Entity")]
    Checkouts,
    #[sea_orm(
        belongs_to = "super::devices::Entity",
        from = "Column::DoorDeviceId",
        to = "super::devices::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Devices,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::access_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccessEvents.def()
    }
}

impl Related<super::checkouts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Checkouts.def()
    }
}

impl Related<super::devices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Devices.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
