//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "access_events")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub event_type: super::sea_orm_active_enums::AccessEventType,
    pub decision: super::sea_orm_active_enums::EventDecision,
    pub device_id: Option<Uuid>,
    pub user_id: Option<Uuid>,
    pub finger_token: Option<String>,
    pub access_session_id: Option<Uuid>,
    pub enrollment_session_id: Option<Uuid>,
    pub message: Option<String>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::access_sessions::Entity",
        from = "Column::AccessSessionId",
        to = "super::access_sessions::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    AccessSessions,
    #[sea_orm(
        belongs_to = "super::devices::Entity",
        from = "Column::DeviceId",
        to = "super::devices::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Devices,
    #[sea_orm(
        belongs_to = "super::enrollment_sessions::Entity",
        from = "Column::EnrollmentSessionId",
        to = "super::enrollment_sessions::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    EnrollmentSessions,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Users,
}

impl Related<super::access_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccessSessions.def()
    }
}

impl Related<super::devices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Devices.def()
    }
}

impl Related<super::enrollment_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EnrollmentSessions.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
