//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "checkouts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    pub access_session_id: Option<Uuid>,
    pub box_device_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub note: String,
    pub photo_path: Option<String>,
    pub photo_mime: Option<String>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::access_sessions::Entity",
        from = "Column::AccessSessionId",
        to = "super::access_sessions::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    AccessSessions,
    #[sea_orm(
        belongs_to = "super::devices::Entity",
        from = "Column::BoxDeviceId",
        to = "super::devices::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Devices,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::access_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccessSessions.def()
    }
}

impl Related<super::devices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Devices.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
