//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "devices")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub name: String,
    pub kind: super::sea_orm_active_enums::DeviceKind,
    pub secret_hash: String,
    pub last_seen_at: Option<DateTimeWithTimeZone>,
    pub is_active: bool,
    /// True on the node that carries the SIM800L.
    pub sms_capable: bool,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::access_events::Entity")]
    AccessEvents,
    #[sea_orm(has_many = "super::access_sessions::Entity")]
    AccessSessions,
    #[sea_orm(has_many = "super::checkouts::Entity")]
    Checkouts,
    #[sea_orm(has_many = "super::enrollment_sessions::Entity")]
    EnrollmentSessions,
    #[sea_orm(has_many = "super::fingerprints::Entity")]
    Fingerprints,
}

impl Related<super::access_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccessEvents.def()
    }
}

impl Related<super::access_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccessSessions.def()
    }
}

impl Related<super::checkouts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Checkouts.def()
    }
}

impl Related<super::enrollment_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EnrollmentSessions.def()
    }
}

impl Related<super::fingerprints::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Fingerprints.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
