//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub email: String,
    #[sea_orm(unique)]
    pub username: String,
    pub password_hash: String,
    pub first_name: String,
    pub middle_name: Option<String>,
    pub last_name: String,
    pub suffix: Option<String>,
    pub phone_number: Option<String>,
    pub role: super::sea_orm_active_enums::Role,
    pub is_active: bool,
    pub last_login_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::access_events::Entity")]
    AccessEvents,
    #[sea_orm(has_many = "super::access_sessions::Entity")]
    AccessSessions,
    #[sea_orm(has_many = "super::checkouts::Entity")]
    Checkouts,
    #[sea_orm(has_many = "super::enrollment_sessions::Entity")]
    EnrollmentSessions,
    #[sea_orm(has_many = "super::fingerprints::Entity")]
    Fingerprints,
    #[sea_orm(has_many = "super::login_events::Entity")]
    LoginEvents,
}

impl Related<super::access_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccessEvents.def()
    }
}

impl Related<super::access_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccessSessions.def()
    }
}

impl Related<super::checkouts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Checkouts.def()
    }
}

impl Related<super::enrollment_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EnrollmentSessions.def()
    }
}

impl Related<super::fingerprints::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Fingerprints.def()
    }
}

impl Related<super::login_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoginEvents.def()
    }
}

impl Model {
    /// How the name is shown anywhere a single string is needed.
    pub fn display_name(&self) -> String {
        [
            Some(self.first_name.as_str()),
            self.middle_name.as_deref(),
            Some(self.last_name.as_str()),
            self.suffix.as_deref(),
        ]
        .into_iter()
        .flatten()
        .map(str::trim)
        .filter(|part| !part.is_empty())
        .collect::<Vec<_>>()
        .join(" ")
    }
}

impl ActiveModelBehavior for ActiveModel {}
